title: 'This is a test title Babita'
video: 'https://youtu.be/5yXQJBU8A28'
develop: 0
description: 'This is a long description'
_core:
  default_config_hash: pSR--8itI0h7yG0riOPbu7NzphQYRYaeMUz4wrADEFs
